### ISSUE TITLE
Error When Adding Variations

### ISSUE THREAD

**Issue by ghost** [SvenKayser/JMOD-Chisel#1]
I'm starting work on updating scripts to JMOD 1.4, which you will find in reteo/Survival-Industry, under "mods".

Minecraft crashes when attempting to execute `Chisel.addVariation`.  Currently using version 2.9.5.11 of Chisel.

Error message:

```
[08/6/2017 13:19:49 PM] java.lang.NoClassDefFoundError: com/cricketcraft/chisel/api/carving/ICarvingVariation
[08/6/2017 13:19:49 PM] 	at com.jeffpeng.jmod.chisel.Scripting.addVariation(Scripting.java:18)
[08/6/2017 13:19:49 PM] 	at jdk.nashorn.internal.scripts.Script$27$\^eval\_.:program(<eval>:37)
[08/6/2017 13:19:49 PM] 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
[08/6/2017 13:19:49 PM] 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
[08/6/2017 13:19:49 PM] 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
[08/6/2017 13:19:49 PM] 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
[08/6/2017 13:19:49 PM] 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
[08/6/2017 13:19:49 PM] 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
[08/6/2017 13:19:49 PM] 	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[08/6/2017 13:19:49 PM] 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
[08/6/2017 13:19:49 PM] 	at com.jeffpeng.jmod.scripting.JScript.evalScript(JScript.java:58)
[08/6/2017 13:19:49 PM] 	at com.jeffpeng.jmod.JMODRepresentation.runScripts(JMODRepresentation.java:112)
[08/6/2017 13:19:49 PM] 	at com.jeffpeng.jmod.JMODLoader.runScripts(JMODLoader.java:200)
[08/6/2017 13:19:49 PM] 	at com.jeffpeng.jmod.JMOD.on(JMOD.java:95)
[08/6/2017 13:19:49 PM] 	at com.jeffpeng.jmod.JMODModContainer.on(JMODModContainer.java:59)
[08/6/2017 13:19:49 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08/6/2017 13:19:49 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08/6/2017 13:19:49 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08/6/2017 13:19:49 PM] 	at java.lang.reflect.Method.invoke(Method.java:498)
[08/6/2017 13:19:49 PM] 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[08/6/2017 13:19:49 PM] 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[08/6/2017 13:19:49 PM] 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[08/6/2017 13:19:49 PM] 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[08/6/2017 13:19:49 PM] 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[08/6/2017 13:19:49 PM] 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[08/6/2017 13:19:49 PM] 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[08/6/2017 13:19:49 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08/6/2017 13:19:49 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08/6/2017 13:19:49 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08/6/2017 13:19:49 PM] 	at java.lang.reflect.Method.invoke(Method.java:498)
[08/6/2017 13:19:49 PM] 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[08/6/2017 13:19:49 PM] 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[08/6/2017 13:19:49 PM] 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[08/6/2017 13:19:49 PM] 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[08/6/2017 13:19:49 PM] 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[08/6/2017 13:19:49 PM] 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[08/6/2017 13:19:49 PM] 	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
[08/6/2017 13:19:49 PM] 	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
[08/6/2017 13:19:49 PM] 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
[08/6/2017 13:19:49 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[08/6/2017 13:19:49 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148)
[08/6/2017 13:19:49 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08/6/2017 13:19:49 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08/6/2017 13:19:49 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08/6/2017 13:19:49 PM] 	at java.lang.reflect.Method.invoke(Method.java:498)
[08/6/2017 13:19:49 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[08/6/2017 13:19:49 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08/6/2017 13:19:49 PM] Caused by: java.lang.ClassNotFoundException: com.cricketcraft.chisel.api.carving.ICarvingVariation
[08/6/2017 13:19:49 PM] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[08/6/2017 13:19:49 PM] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[08/6/2017 13:19:49 PM] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[08/6/2017 13:19:49 PM] 	... 47 more
[08/6/2017 13:19:49 PM] Caused by: java.lang.NullPointerException
[08/6/2017 13:19:49 PM] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[08/6/2017 13:19:49 PM] 	at lumien.perfectspawn.Transformer.PSClassTransformer.transform(PSClassTransformer.java:43)
[08/6/2017 13:19:49 PM] 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[08/6/2017 13:19:49 PM] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[08/6/2017 13:19:49 PM] 	... 49 more
```
